### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pachi81**

### CODE REVIEW

**Comment by pachi81** [comment]
@froster82 some small changes to readme...

**Review by froster82 — APPROVED** [review]
All OK

**Comment by froster82** [comment]
OK, too quick. I opened only the last change. Will translate the rest.

**Comment by pachi81** [comment]
@froster82 can you update this text: https://github.com/pachi81/GlucoDataHandler/pull/119/commits/d692e7fb5634a0cc0343c01d4b1a63fcde3f932e

**Comment by pachi81** [comment]
@froster82 need some more readme translation, but not many:
https://github.com/pachi81/GlucoDataHandler/blob/readme/README_PL.md#funkcje  -> the nightscout "pebble interface"
and
https://github.com/pachi81/GlucoDataHandler/blob/readme/README_PL.md#%C5%BAr%C3%B3d%C5%82a

**Comment by froster82** [comment]
@pachi81 I need to read some more on pebble interface in Polish to translate it properly. I do not use NS so I am not sure if I should give some Polish name for it or just leave it as is.

**Comment by pachi81** [comment]
Pebble is a name, should be the same in polish. Interface or endpoint can be used...

**Pull request merged**
