### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by pachi81**

### CODE REVIEW

**Comment by pachi81** [comment]
@froster82 can you check the strings: https://github.com/pachi81/GlucoDataHandler/pull/128/files#diff-0908d478f1e1608a4d8bf0d6e84f3c23dd963a61f2ff17a7984af7e3e9f938d1

I had to create a new version as google want to reject my wear app as there is something missing,,, :-(

**Review by froster82 — APPROVED** [review]
PL strings all ok.

**Comment by froster82** [comment]
I see you have already incorporated IOB from Juggluco. That is great news. I only wonder if Juggluco will allow to change insulin profiles. Now my Fiasp level in Juggluco is not the same as in xDrip. We'll just have to wait and see.

**Comment by pachi81** [comment]
> I see you have already incorporated IOB from Juggluco. That is great news. I only wonder if Juggluco will allow to change insulin profiles. Now my Fiasp level in Juggluco is not the same as in xDrip. We'll just have to wait and see.

Yes it is different everywhere, nightscout, juggluco and xDrip.
For xdrip you can use local webservice to receive iob using nightscout source as additional source to jugglico.

**Pull request merged**
