### PR TITLE
vNext

### PR DESCRIPTION
**Pull request by pachi81**
Bugfixes for current version

### CODE REVIEW

**Comment by pachi81** [comment]
@froster82 @dinizmauricio 
I have to create a new version with some bugfixes, as my changes on the alarms will take some time...
Can you please update your language file for the parts at the bottom under new.
Thank you!

**Comment by froster82** [comment]
@pachi81, I will deal with it as soon as I can. Tomorrow, I have a lot on ny plate, but will do my best.

**Comment by pachi81** [comment]
@froster82 No problem!

**Review by froster82 — APPROVED** [review]
Polish part done.

**Comment by pachi81** [comment]
@froster82 @dinizmauricio
The new version is online for testing. Please check, if everything is fine.
@dinizmauricio I granted you access to this repo, so you can change the strings directly in this commit.
Please provide feedback, even if everything is fine for you.
Thank you!

**Comment by froster82** [comment]
@pachi81 app seems to work ok, but there is a bug with lockscreen wallpaper. The option itself works fine, but when I turned it off, the phone restored not my previous wallpaper (the one I used to hqve before switching on the option in GDH, but the default wallpaper and lockscreen wallpaper the phone had in the beginning of its use. 
Also the message in the app says press here to go directly to nitification settings. When I press, nothing happens.
See screens. 
Screenshot_20240414-195747_GlucoDataHandler
Screenshot_20240414-195940_GlucoDataHandler
Screenshot_20240414-200006_One UI Home

**Comment by dinizmauricio** [comment]
Is there a compiled apk version? Is it on the Google Play store? It didn't appear to me.

**Comment by froster82** [comment]
@dinizmauricio, hi! Check your Google Play and GDH there. You should have info that this is a beta version for internal testing. If so, you should have an update to download.

**Comment by pachi81** [comment]
> @pachi81 app seems to work ok, but there is a bug with lockscreen wallpaper. The option itself works fine, but when I turned it off, the phone restored not my previous wallpaper (the one I used to hqve before switching on the option in GDH, but the default wallpaper and lockscreen wallpaper the phone had in the beginning of its use. Also the message in the app says press here to go directly to nitification settings. When I press, nothing happens. See screens. Screenshot_20240414-195747_GlucoDataHandler Screenshot_20240414-195940_GlucoDataHandler Screenshot_20240414-200006_One UI Home

Oh, damn, this shouldn't be part of this version, as it contains info for alarms. 
Thank you for pointing me to this, I will remove this message.

**Comment by pachi81** [comment]
The problem with the wallpaper may be related to your phone. Which one do you have?
I will check, if I have any influence to reset the old wallpaper. But on my phones it is working ☹️

**Comment by dinizmauricio** [comment]
> @dinizmauricio, hi! Check your Google Play and GDH there. You should have info that this is a beta version for internal testing. If so, you should have an update to download.

Thanks @froster82 ! It hasn't appeared here yet, I'll wait a little longer.

print

**Comment by froster82** [comment]
@pachi81 I have Samsung Galaxy S 9 on Android 10. Oldie but still works fine :)

**Comment by pachi81** [comment]
> > @dinizmauricio, hi! Check your Google Play and GDH there. You should have info that this is a beta version for internal testing. If so, you should have an update to download.
> 
> Thanks @froster82 ! It hasn't appeared here yet, I'll wait a little longer.
> 
> print

Can you check this link:
https://play.google.com/apps/internaltest/4701605738754095200

**Comment by pachi81** [comment]
> @pachi81 I have Samsung Galaxy S 9 on Android 10. Oldie but still works fine :)

I have an S10e with Android 12.
But I will check in emulator. On my device it is also working with the link to app notifications...

**Comment by dinizmauricio** [comment]
Now it works, I'll test it here. Thanks!

**Comment by froster82** [comment]
> I have an S10e with Android 12. But I will check in emulator. On my device it is also working with the link to app notifications...

Maybe Iit is a question of the Polish version? Maybe the hyperlink is missing in the string?

**Comment by pachi81** [comment]
> > I have an S10e with Android 12. But I will check in emulator. On my device it is also working with the link to app notifications...
> 
> Maybe Iit is a question of the Polish version? Maybe the hyperlink is missing in the string?

No, it is a system call. Can you press it and send the logs to the mail? Thank you!

**Comment by froster82** [comment]
Logs sent.

**Comment by dinizmauricio** [comment]
print

I noticed that the String is not complete, it is missing: de.michelinside.glucodatahandler


I have been using the app integrated with Nightscout. I'm trying to get data from Xdrip, I followed the steps but the data hasn't arrived yet.

**Comment by pachi81** [comment]
> I noticed that the String is not complete, it is missing: de.michelinside.glucodatahandler

Strange, seems to be cut off. But the german string is longer and on my phone it is not cut off.
So maybe I have to divide this string into two parts.

> I have been using the app integrated with Nightscout. I'm trying to get data from Xdrip, I followed the steps but the data hasn't arrived yet.

I tested it today and it works like expected. Can you recheck you xDrip-settings:
https://github.com/pachi81/GlucoDataHandler/blob/vNext/SOURCES.md#xdrip

**Comment by froster82** [comment]
@pachi81 the string about xDrip is also cut in the Polish version. 
Screenshot_20240415-132410_GlucoDataHandler

**Comment by pachi81** [comment]
@froster82 @dinizmauricio New version is available which should fix the reported issues. Many thank for reporting!!!

But as this does not solves my problem, I added a setting for the colored status bar icon to deactivate it. Can you please translate the two new string. 
Thank you!

**Comment by dinizmauricio** [comment]
> @froster82 @dinizmauricio New version is available which should fix the reported issues. Many thank for reporting!!!
> 
> But as this does not solves my problem, I added a setting for the colored status bar icon to deactivate it. Can you please translate the two new string. Thank you!

Adjusted for portuguese

**Comment by pachi81** [comment]
> I still don't understand what I should do to make the wear work :/

@dinizmauricio For any reason, the first connection sometimes have problems. 
Please try to touch on wear on "Phone: disconnected" and on phone und the related label (it will re-check connection in the background).
If it does not work, please restart watch.

**Comment by pachi81** [comment]
@froster82 @dinizmauricio Thank you for your fast translation! New version is online.

**Comment by froster82** [comment]
Ok, no worries. Just wanted to let you know that this might happen.
I changed the Polish translation for rate in string 8. I had some questions about it, but was not sure how to correct it. Now I checked the German string and trend in Polish will also be better.

**Comment by froster82** [comment]
@pachi81, I found another bug, which was not present previously.
Widget on the main screen is not refreshed properly, when no current value arrives. It used to be greyed out and crossed out automatically.
My circumstances: my source is my watch. I have a widget on the phone. During the night watch is put to sleep mode, so the GDH broadcast is silenced. The phone does not receive data and greys out the widget. Today the widget got stuck on the last value it received and was green all the time. I retested it - went with the watch out of phone reach and when I came back widget was also stuck. The app itself however shows everything ok - crossed out value. 
A newly introduced widget swows everything ok.
Pasting screens below. 

Screenshot_20240416-065144_One UI Home
Screenshot_20240416-065203_GlucoDataHandler
Screenshot_20240416-065233_One UI Home
Screenshot_20240416-073608_One UI Home
Screenshot_20240416-073624_GlucoDataHandler

**Comment by pachi81** [comment]
>  A newly introduced widget swows everything ok. Pasting screens below.

@froster82 the new widget is working correct? So it may happen, that during an upgrade, the widget connection gets lost. Also the notification connection may get lost. I have no idea, why this is happen sometime. In this situations, you have to restart you phone or re-add the widget.
If it happened again, please send me the logs.

**Comment by froster82** [comment]
@pachi81, when the connection is restored, the widget is refreshed again and later shows everything fine. But it is not greyed out and crossed out when it is out of reach of the source. No need to restart the phone or add new widget. As if the sole picture of the crossed out value is not sent to the widget when it loses the connection.

**Comment by pachi81** [comment]
> @pachi81, when the connection is restored, the widget is refreshed again and later shows everything fine. But it is not greyed out and crossed out when it is out of reach of the source. No need to restart the phone or add new widget. As if the sole picture of the crossed out value is not sent to the widget when it loses the connection.

@froster82 Now, I understand. Yes, I have tested. You are right! I´m using the widget with timestamp and this seems to be working. But the one without, is not working. I will check and fix. Thank you!

**Comment by froster82** [comment]
@pachi81, I had a chance to test the widget bug. When the value and trend are greyed out and crossed in the app, they are not on the widget. When the app completely loses the value and trend, the widget also loses its stuck values. A bit strange. Again, when the connection is resumed, everything comes back to normal. 
Screenshot_20240417-172059_GlucoDataHandler
Screenshot_20240417-172109_One UI Home

**Comment by pachi81** [comment]
@froster82 this happens with the latest versuon? Please send me the logs, if it happened!
Thank you!

**Comment by froster82** [comment]
@pachi81, yes this was today. I sent the log to your email address.

**Comment by froster82** [comment]
@pachi81, now I turned off bluetooth completely in the phone, waitwd for about 5 minutes and... the app and thr widget got grey and crossed out. Now it works all as it should. Will try to replicate my previous behaviour and circumstances tomorrow, but it seem everything ia ok.
Sorry for false alarm.

**Comment by pachi81** [comment]
> @pachi81, now I turned off bluetooth completely in the phone, waitwd for about 5 minutes and... the app and thr widget got grey and crossed out. Now it works all as it should. Will try to replicate my previous behaviour and circumstances tomorrow, but it seem everything ia ok. Sorry for false alarm.

@froster82  Not sure, if it was really false alarm, but I hope 😉
Please have a look from time to time on widget and notification and if it happens again, send me the logs.
Thank you very much for your testing!

**Comment by froster82** [comment]
Ok, not a false alarm ;/
I described everything in the email with screens and logs.

**Pull request merged**
