### PR TITLE
version 1.2

### PR DESCRIPTION
**Pull request by pachi81**

### CODE REVIEW

**Comment by pachi81** [comment]
@froster82: new strings are available: https://github.com/pachi81/GlucoDataHandler/blob/170deef2606913a442b637d6c29639b542b3e234/common/src/main/res/values-pl/strings.xml#L533

**Comment by pachi81** [comment]
@Cheun1: new string are available: https://github.com/pachi81/GlucoDataHandler/blob/170deef2606913a442b637d6c29639b542b3e234/common/src/main/res/values-fr/strings.xml#L545

**Comment by froster82** [comment]
Hi Michael! Thanks for another update. 
I updated my part.

When I have a chance, let me also describe one thing which could possibly be changed, as far as alarms are concerned.
When we have a high alarm set to e.g. 160, and the glucose value is rising steadily, at some point there is a time when the glucose value (GV) crosses the border (160) and the alarm is triggered and I disable the alarm. But then the GV comes down for a bit, because it varies around the border, and after a minute or so it again crossed the border (160), and the alarm is triggered again. And sometimes again if the GV is zigzagy - fairly stable but falling and rising around the border value. This happens irrespective of the retrigger setting, because if retrigger is set to e.g. 10 minutes, the situation described above happens anyways before the 10 minutes have expired.
Would it be possible to introduce a time buffer for the alarm? Once triggered and disabled, the alarm would not be triggered again if the same condition appears within a specified time?

**Review by froster82 — APPROVED** [review]

**Comment by pachi81** [comment]
> Hi Michael! Thanks for another update. I updated my part.
> 
> When I have a chance, let me also describe one thing which could possibly be changed, as far as alarms are concerned. When we have a high alarm set to e.g. 160, and the glucose value is rising steadily, at some point there is a time when the glucose value (GV) crosses the border (160) and the alarm is triggered and I disable the alarm. But then the GV comes down for a bit, because it varies around the border, and after a minute or so it again crossed the border (160), and the alarm is triggered again. And sometimes again if the GV is zigzagy - fairly stable but falling and rising around the border value. This happens irrespective of the retrigger setting, because if retrigger is set to e.g. 10 minutes, the situation described above happens anyways before the 10 minutes have expired. Would it be possible to introduce a time buffer for the alarm? Once triggered and disabled, the alarm would not be triggered again if the same condition appears within a specified time?

Hi @froster82,
normally it should work, as you expected. If the alarm crosses a border and triggers, it should trigger again, before the 10 minutes are over. If it does not work for you, please send me the logs, after it happens.

Michael

**Comment by froster82** [comment]
Michael, thanks, I will try to catch that,
It happened a couple of times in the night and was really bothersome, because I woke up, swiped the alarm away and after a minute or so this happened again.

**Comment by pachi81** [comment]
@froster82 one more small translation:
https://github.com/pachi81/GlucoDataHandler/blob/f87aa1b9b63415633eee83e09aca201334a57390/common/src/main/res/values-pl/strings.xml#L458

**Comment by froster82** [comment]
@pachi81, I translated the string, but in the English version I would change one small bit. Instead of writing most watchfaces, I would use "watchfaces giving such a possibility', because e.g. in TicWatch there are not so many standard watchfaces with customisable complications. Just a precaution :)

**Comment by pachi81** [comment]
@froster82 new test version is online, if you haven´t it already...

**Comment by froster82** [comment]
@pachi81, thanks. I installed it and will test.
One thing I noticed is that Quiet hours cannot be enabled unless you first set the hours. This might not be so clear at first.
Second - alarm repeat function. My short alarm sound now keeps playing and playing. And the shortest time for playing it is now 1 minute, or 30 seconds if the auto notification disable option is enabled. 
Can we swap minutes for seconds? Instead of a slider, there could be a field where you could just enter the value - eg. repeat the alarm sound for 10 seconds, then stop.

**Comment by pachi81** [comment]
> @pachi81, thanks. I installed it and will test. One thing I noticed is that Quiet hours cannot be enabled unless you first set the hours. This might not be so clear at first. Second - alarm repeat function. My short alarm sound now keeps playing and playing. And the shortest time for playing it is now 1 minute, or 30 seconds if the auto notification disable option is enabled. Can we swap minutes for seconds? Instead of a slider, there could be a field where you could just enter the value - eg. repeat the alarm sound for 10 seconds, then stop.

Thanks for the feedback, the problem with quiet hours, the hours have to be set, before it can be enabled, otherwise people would not set hours... But I know, what you are meaning, but not sure, what is the best way...

For the repeat option. Normally you would stop it, if you recognize it and if you do not recognize, it is not important, if it takes 30s or 1 minute... I´m not sure, if it make sense, but yes, a minute can be a long time... The biggest problem is, that I do not like the edit fields, as they do not provide a unit or any other information. A slider with seconds will get too long to handle it with fingers...
I personal use the sound delay, so I have 10 seconds without sound, before the sound is playing.

**Comment by froster82** [comment]
> Thanks for the feedback, the problem with quiet hours, the hours have to be set, before it can be enabled, otherwise people would not set hours... But I know, what you are meaning, but not sure, what is the best way...

Maybe just a short note in the description that in order for the option to get active, the hours must be set first.

**Comment by pachi81** [comment]
> I think we now have not so clear alarm options and I do not know which option is for what :) Too many repeats and re-enables. Maybe a change in wording would be better. What would you say if there was "Alarm sound length" option somewhere there?

You are right, I also thought about an expert mode, to hide some setting for default... 
The problem is, if I remove or merge settings to new one, people will complain, that the feature is "gone". I´m still not sure, if it really needs the repeat option, if the sound is too short, the users can select a longer one...

**Comment by froster82** [comment]
> I´m still not sure, if it really needs the repeat option, if the sound is too short, the users can select a longer one...

I think you are right. The repeat option now causes a bigger problem than it presents a real value.

**Comment by pachi81** [comment]
> > Thanks for the feedback, the problem with quiet hours, the hours have to be set, before it can be enabled, otherwise people would not set hours... But I know, what you are meaning, but not sure, what is the best way...
> 
> Maybe just a short note in the description that in order for the option to get active, the hours must be set first.

But it is already part of the description:
`No alarm notifications for this alarm during quiet hours. Configure your preferred times to use this feature.`

**Comment by froster82** [comment]
> But it is already part of the description:
> `No alarm notifications for this alarm during quiet hours. Configure your preferred times to use this feature.`

OK, so my translation needs to be corrected, because I understood it in a more general way. English version is clearer now.

**Comment by pachi81** [comment]
> > But it is already part of the description:
> > `No alarm notifications for this alarm during quiet hours. Configure your preferred times to use this feature.`
> 
> OK, so my translation needs to be corrected, because I understood it in a more general way. English version is clearer now.

I had a long discussion with Gemini about a good text in englisch... :-D

**Comment by pachi81** [comment]
> > But it is already part of the description:
> > `No alarm notifications for this alarm during quiet hours. Configure your preferred times to use this feature.`
> 
> OK, so my translation needs to be corrected, because I understood it in a more general way. English version is clearer now.

That´s why it is good, that you are testing your translation in the app itself... 
Thank you for all your feedback!!!

**Comment by froster82** [comment]
> Thank you for all your feedback!!!

My pleasure :) I really enjoy your app and appreciate your work.

One more thing I must check is Talkback options, But I cannot find those options to check if the Polish text works. I might dig into options some more in the evening.

**Comment by froster82** [comment]
@pachi81, I found a bug. Related to repeat function. It cannot be turned off or the duration cannot be changed. Tried to set it to 1 minute, 0, -1, but iy always comes back to the default 5. I tested it on low alarm. Log attached. 
[GDH_PHONE_APP_20241011_200840.txt](https://github.com/user-attachments/files/17346139/GDH_PHONE_APP_20241011_200840.txt)

**Comment by pachi81** [comment]
> @pachi81, I found a bug. Related to repeat function. It cannot be turned off or the duration cannot be changed. Tried to set it to 1 minute, 0, -1, but iy always comes back to the default 5. I tested it on low alarm. Log attached. [GDH_PHONE_APP_20241011_200840.txt](https://github.com/user-attachments/files/17346139/GDH_PHONE_APP_20241011_200840.txt)

What do you mean. In code it will be changed. Or do you mean the settings? Maybe it will not been loaded correct. But it will be removed, so no problem...

**Comment by pachi81** [comment]
New version available...

**Comment by froster82** [comment]
@pachi81 can you check if dismissing alarm on the phone also dismisses the alarm on the wear? In my case, low alarm was activated on both phone and wear, I swiped it away on the phone, but it kept vibrating on the wear until I swiped it away. Dismissing it on the phone did not dismiss it on the wear. I need to test it some more, but this is to be checked. 
[GDH_PHONE_APP_20241012_124906.txt](https://github.com/user-attachments/files/17349745/GDH_PHONE_APP_20241012_124906.txt)
[GDH_WEAR_APP_20241012_124458.txt](https://github.com/user-attachments/files/17349746/GDH_WEAR_APP_20241012_124458.txt)

**Comment by pachi81** [comment]
> @pachi81 can you check if dismissing alarm on the phone also dismisses the alarm on the wear? In my case, low alarm was activated on both phone and wear, I swiped it away on the phone, but it kept vibrating on the wear until I swiped it away. Dismissing it on the phone did not dismiss it on the wear. I need to test it some more, but this is to be checked. [GDH_PHONE_APP_20241012_124906.txt](https://github.com/user-attachments/files/17349745/GDH_PHONE_APP_20241012_124906.txt) [GDH_WEAR_APP_20241012_124458.txt](https://github.com/user-attachments/files/17349746/GDH_WEAR_APP_20241012_124458.txt)

OK, the watch wasn´t ready, when the notification appears on phone, so the watch only shows the notification from phone and maybe its vibration. I do not see any alarm triggered by watch itself. So just keep an eye on...
Thank you!

**Comment by pachi81** [comment]
Found another urgent issue for alarm. New version available...

**Comment by froster82** [comment]
My issue in the new version works as intended. Watch stops the alarm when notification is swiped away on the phone. Nothing else noticed so far.

**Comment by pachi81** [comment]
Just uploaded version .22

**Comment by pachi81** [comment]
@froster82 need one more translation:
```
Open Integration and enable "Share data with GWatch"
Remark: the DiaBox broadcast only contains the glucose value and no more information like trend!
```
Gemini did this:
```
Otwórz Integrację i włącz "Share data with GWatch"
Uwaga: transmisja DiaBox zawiera tylko wartość glukozy i żadnych dodatkowych informacji, takich jak trend!
```

**Comment by froster82** [comment]
@pachi81, not so bad :)
If this is some option in Diabox, the translation would be as follows:

Otwórz menu Integracja i włącz opcję "Share data with GWatch" (udostępnij dane aplikacji GWatch). 
Uwaga: transmisja DiaBox zawiera tylko wartość glukozy i żadnych dodatkowych informacji, takich jak trend!

**Comment by pachi81** [comment]
@froster82 One more translation needed:
`The AAPS broadcast from BYODA doesn't seem to work with other apps. Please use the xDrip+ broadcast in BYODA!`

Thank you!

**Comment by froster82** [comment]
@pachi81 , here it goes:

Uwaga: zdaje się, że transmisja AAPS z BYODA nie działa z innymi aplikacjami. W BYODA należy używać transmisji xDrip+!

**Comment by pachi81** [comment]
@froster82 Hi some new strings for GDA at the end of the file.
But you have time, I have holidays for a week. ;-)

**Comment by froster82** [comment]
@pachi81, OK, I'll have a look at them.
Have a good time!

**Comment by pachi81** [comment]
@froster82 Sorry, but I need one more translation...
Thank you for all your work!!!

**Comment by froster82** [comment]
@pachi81, done. I will need to check in the app if it fits the specific context, though :)
Thank you for your work!

**Comment by pachi81** [comment]
> @pachi81, done. I will need to check in the app if it fits the specific context, though :) Thank you for your work!

@froster82: context is to disable the alarm icon in the main screen to prevent disable alarms accidentally.

**Comment by froster82** [comment]
Ok, so my translation needs a bit of correction :)

**Comment by pachi81** [comment]
New version 1.2 is online for testing.

**Pull request merged**
