### PR TITLE
Develop GDA

### PR DESCRIPTION
**Pull request by pachi81**
GlucoDataAuto changes for version 1.0

### CODE REVIEW

**Comment by pachi81** [comment]
@froster82 @dinizmauricio 
I added some changes for GlucoDataAuto. I translated all string with ChatGPT (just for interest). Can you check the translation?
Thank you!
(No hurry, as I do not release it in the next week, I´m still testing it!)

**Review by froster82 — APPROVED** [review]

**Comment by froster82** [comment]
@pachi81, in general the Polish version was not bad. It was fully usable. I only changed it to be more user friendly, because Polish requires a bit of a creative approach ;)

**Comment by pachi81** [comment]
> @pachi81, in general the Polish version was not bad. It was fully usable. I only changed it to be more user friendly, because Polish requires a bit of a creative approach ;)

@froster82 Same for german translation, I only had to change some minor things to be more user friendly.

Thank you also for the englisch fixes. ChatGPT does not point me to that, but I haven't asked... 🤣

**Comment by pachi81** [comment]
@froster82 Can you re-check the new strings?
I have found another bug (end of snooze is not recognized correct), so I have to create another fix.
So, you can also change the strings, I added.

**Comment by froster82** [comment]
@pachi81 , only some minor changes were required, because official Polish strings in AA are a bit different. Otherwise it was all OK.

**Comment by pachi81** [comment]
@froster82 One more change to the help for GDA (hopefully the last one):
https://github.com/pachi81/GlucoDataHandler/pull/153/commits/f3620386910c777ef4c2d9c4240be60506c38ae8#diff-0908d478f1e1608a4d8bf0d6e84f3c23dd963a61f2ff17a7984af7e3e9f938d1

**Comment by froster82** [comment]
@pachi81, everything looks fine. In PL and ENG strings.

**Comment by pachi81** [comment]
> @pachi81, everything looks fine. In PL and ENG strings.

@froster82 Perfect! Thank you! So I can release the next GDA version :-)

**Pull request merged**
