### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by pachi81**

### CODE REVIEW

**Comment by pachi81** [comment]
@froster82 Can you also update the settings for GlucoDataAuto:
https://github.com/pachi81/GlucoDataHandler/pull/124/files#diff-0908d478f1e1608a4d8bf0d6e84f3c23dd963a61f2ff17a7984af7e3e9f938d1
-> https://github.com/pachi81/GlucoDataHandler/blob/develop/common/src/main/res/values-pl/strings.xml

**Comment by froster82** [comment]
@pachi81 , both done. But the Readme is still visible in the old form, even though I saved it. Can you check it?

**Comment by pachi81** [comment]
> @pachi81 , both done. But the Readme is still visible in the old form, even though I saved it. Can you check it?

@froster82  Not in the readme branch: https://github.com/pachi81/GlucoDataHandler/blob/readme/GlucoDataAuto_PL.md
But I can not merge readme before the new version is life...

**Comment by froster82** [comment]
@pachi81 when I open the link you provided in the other thread and go to Readme I cannot edit it, because ot says I need to be on a branch. I somehow edited it somewhere else, but don't remember where exactly. Do you still need me to change or edit something in this case?

**Comment by pachi81** [comment]
Ah, you are right... Strange, it works the first time... 
But it is all ok, now. So at the moment, there is no further change.

**Pull request merged**
