### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by pachi81**

### CODE REVIEW

**Comment by pachi81** [comment]
@froster82: I need a small translation:
https://github.com/pachi81/GlucoDataHandler/pull/137/files#diff-0908d478f1e1608a4d8bf0d6e84f3c23dd963a61f2ff17a7984af7e3e9f938d1

Thank you! Is not urgent!

**Comment by froster82** [comment]
@pachi81 PL version of 299-300 done.
IoB in Juggluco ver. 7.5.0 still not available ;/

**Review by froster82 — APPROVED** [review]

**Comment by pachi81** [comment]
@froster82 I have changed some more string for GlucoDataAuto.
Can you translate them? Thank you!

I also have tried the last version of Juggluco and it is gone. jka also does not answer to my feature request, so it seems, he does not want it...

**Comment by froster82** [comment]
@pachi81, I will take a look at them tomorrow.
As for JKA, try and write to him in an email. I always get an answer when I write that way.

**Comment by pachi81** [comment]
@froster82 Hi, I need some more translation, as google forced me, to remove the automatically set a permission. Now, I have to ask the user...

**Comment by froster82** [comment]
@pachi81, hi! I will read about the wording of those permissions in Polish and will translate it. Do you have the German version for 'schedule exact alarm'? Sometimes it's easier to find the right Polish equivalent using also German.

**Comment by pachi81** [comment]
This is the setting I mean. In code it is called SCHEDULE EXACT ALARM...
Screenshot_20240310_214202_Settings

It is used to trigger the app after an interval for example for the obsolete values or to request data from nightscout or librelink.

**Comment by pachi81** [comment]
@froster82 I have updated the strings again and removed the part with google, as it is not relevant...
Here is the german to polish translation:

```
W przypadku wszystkich zadań związanych z czasem i interwałami aplikacja wymaga autoryzacji alarmów i przypomnień.
Aplikacja nie zmienia żadnych alarmów ani przypomnień skonfigurowanych przez użytkownika. Wymaga jedynie autoryzacji dla wewnętrznych wyzwalaczy.
Po naciśnięciu przycisku OK aplikacja przekieruje użytkownika do odpowiednich ustawień autoryzacji. Należy aktywować tę autoryzację dla GlucoDataHandler.
```

**Comment by froster82** [comment]
@pachi81 I didn't mean translation already into Polish ;) I can deale with that ;) Sometimes, however, when I am not familiar with the exact vocabulary concerning a specific field, it is easier to have two language versions. German is a bit more similar to Polish in some cases, because we have a lot more borrowings form German than form English.

**Comment by pachi81** [comment]
@froster82 OK, I get it :-)
Yes, in English there are less words, so I know, what you are meaning. You can always check the German translation in the related string files:
https://github.com/pachi81/GlucoDataHandler/pull/137/files#diff-1369f26acce2dcc2d7d2807f3ebe092dd654da291430c78db8f1fe1491df65d5

Add the moment I´m really annoyed by Google policies... Which each release they are finding a new reason for reject my app. This setting for example, I´m using since the beginning of my app and now, they complain about :-(

**Comment by froster82** [comment]
@pachi81, Polish version done. That above screen really helped me a lot, because in my Android 10 I think I do not have this permission required. I hope Google doesn't mess around with you too much and you will be able to deal with all their complaining.

**Comment by froster82** [comment]
@pachi81 on A10 everything looks fine. No errors or crashes.

**Comment by froster82** [comment]
@pachi81, hi! I am writing with an idea for future development. 
One parent on the Polish FB group suggested that it would be useful to have a log of say 5 recent delta changes. This would show the rate of glucose change. Of course, if possible, you could log and show on a widget the glucose level, delta from the previous value, and maybe time.
This is just an idea to consider. What do you think? 
Have a nice day!

**Comment by pachi81** [comment]
@froster82 I don´t think, this make sense. This sounds more like a graph, where you can see it. And graph support will come later.
I think a better way is doing it like in AAPS to have a delta/minute, delta/5 minutes and delta/15 minutes.
But also for these values I need historical values, which will come with the graph...

**Comment by froster82** [comment]
OK, this was just an idea based on the lack of graph - so far. But if you plan to introduce it in the future, then you are right - it loses its validity :)

**Pull request merged**
