### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by pachi81**

### CODE REVIEW

**Comment by pachi81** [comment]
@froster82 Hi, there are some new translation for you:
https://github.com/pachi81/GlucoDataHandler/pull/105/files#diff-0908d478f1e1608a4d8bf0d6e84f3c23dd963a61f2ff17a7984af7e3e9f938d1

I moved all strings to one file, hopefully it will be easier for you.
Regards, Michael

**Comment by pachi81** [comment]
> Hi, Michael! This time, I will need some time for that. I will try to take a look at those after the weekend, unless I am able to sit on it on Sunday.

No problem! I still testing the app and all changes.
If you want to try it out and see, what the resources are used for, here you can download a beta version:
[https://onedrive.live.com/?authkey=%21AG8eUfvdnCAQ1G4&id=F01898105C58ADFA%211299367&cid=F01898105C58ADFA](https://deref-web.de/mail/client/eP9benNcieE/dereferrer/?redirectUrl=https%3A%2F%2Fonedrive.live.com%2F%3Fauthkey%3D%2521AG8eUfvdnCAQ1G4%26id%3DF01898105C58ADFA%25211299367%26cid%3DF01898105C58ADFA)

**Comment by pachi81** [comment]
@froster82 just for your information, I also update the README_PL file:
https://github.com/pachi81/GlucoDataHandler/pull/105/files#diff-848c6b7f55482ba95c7344490ee2096fdaf4e34bb9cb80d43cac1694ec450972

Have a nice weekend!

**Review by froster82 — COMMENTED** [review]
Updated Polish parts.

**Comment by froster82** [comment]
@pachi81 Hi, I updated the strings and readme files. Please let me know if everything is ok.

**Comment by pachi81** [comment]
> @pachi81 Hi, I updated the strings and readme files. Please let me know if everything is ok.

Great! Thank you! Maybe I have to add some more changes later, because I´m still in progress and found some additional problems. 
@froster82  I thought about using google translator, so you only have to check, if the google translation is ok or bullshit :-)
Would it be easier for you or is it better to translate the englisch text?

**Comment by froster82** [comment]
@pachi81 , no, please don't go that way! :D It would be a lot harder and more time-consuming to correct after google translate. English is just fine.

**Comment by pachi81** [comment]
@froster82 I did some more changes. Can you also change the string from this commit:
https://github.com/pachi81/GlucoDataHandler/pull/105/commits/b68dde909c13b7b4b690e415b3a6567d868f476a
Thank you!

**Comment by froster82** [comment]
This time you caught me with a free moment, so strings are ready :)

**Comment by pachi81** [comment]
@froster82 one more very small string (no_new_value): https://github.com/pachi81/GlucoDataHandler/pull/105/commits/d0a744af33d0caad8634988ae6251d4b9f82d953#diff-0908d478f1e1608a4d8bf0d6e84f3c23dd963a61f2ff17a7984af7e3e9f938d1

Thank you very much for you support!!!

**Comment by froster82** [comment]
@pachi81 Done.
It is I who should be thanking you for a great app. It's getting better and better with every version, so I really hope you keep up the great work! Thanks!

**Review by froster82 — COMMENTED** [review]
PL updated

**Comment by pachi81** [comment]
@froster82 just one question, now you are using minuty for mintues, but for source_request_interval_5 you are using 5 minut.
Is this correct? For no_new_value we do not need the brackets, as the value is always greater then 1.

**Comment by froster82** [comment]
In Polish we have cases just line in German. For no new value I did not know what the value would be, that is why I gave an option - no new value since 1 minute would be "od 1 minuty", but everything greater than 1 would be "od 2-99 minut". If you say that 1 would not appear there, "minut" would be better.

**Comment by pachi81** [comment]
> In Polish we have cases just line in German. For no new value I did not know what the value would be, that is why I gave an option - no new value since 1 minute would be "od 1 minuty", but everything greater than 1 would be "od 2-99 minut". If you say that 1 would not appear there, "minut" would be better.

@froster82 thank you! I have changed it. Last question, 1 minuta is also correct? Because in german there is only one "Minute" for 1.

**Comment by froster82** [comment]
Yes, this is correct. We have maaaaany suffixes ;) 1 minuta, 2 minuty but 5 minut.
And also many versions of the same word for different persons in singular an plurar.
atgcvmy44jba1

**Review by froster82 — APPROVED** [review]

**Pull request merged**
