### PR TITLE
Fix #115, resolves #95, resolves #109

### LINKED ISSUE #109: Add Support for BangleJS
Gude,

I've made an app a while ago, to be able to send blood glucose values to a BangleJS watch. I think this bit of code would be beneficial for your projet, or do you want to only support googles war os? If you are interested in this, give me a ping and I will create a pull request in the future. :) Here is a link to my app: https://codeberg.org/phrogg/BG2BangleJSApp already in F-Droid. 

Alles jute
Phil

### LINKED ISSUE #115: mmol/l unchecked constantly
Option "Use mmol/l" in Settings-> General menu, constantly unchecking. 
For last day- twise. 
Using last version from Play store ( 0.9.8).

PS. Big thanks for you work!

### PR DESCRIPTION
**Pull request by pachi81**

### CODE REVIEW

**Comment by froster82** [comment]
@pachi81 Hi! I just have a quick question. Do you have any news about alarms functionality? I had a moment to prepare a manual for using GDH as a LibreLink Follower and this alarm feature on parents' phone could really be useful. If this is going to be available anytime soon, I will just hold on to the text and wait for a new release to include a description for activating alarms.

**Comment by pachi81** [comment]
> @pachi81 Hi! I just have a quick question. Do you have any news about alarms functionality? I had a moment to prepare a manual for using GDH as a LibreLink Follower and this alarm feature on parents' phone could really be useful. If this is going to be available anytime soon, I will just hold on to the text and wait for a new release to include a description for activating alarms.

Hi,
I know, that many people asked for... At the moment, I only have limited time and so much todo...
I want todo a refactor of the UI to be easier to use. I want to add support for IOB and COB...
So, I don´t know, when I can implement the alarm feature. The biggest problem, I want to have some good solution with snooze an alarm, provide different settings, ... 
Also I have less experience with alarm notification for dnd and so on.
That is the reason, I am procrastinating it at the moment ;-) 
But yes, I have to do it... but it can take some weeks. Hopefully faster...

**Comment by froster82** [comment]
I get it and totally understand :D In that case I will post my manual and later update it with alarms function, when it is available. Thanks!

**Comment by froster82** [comment]
It's me again :) 
Today I recommended GDH to somebody with iOS on her phone and a watch with WearOS. She wanted to get gluco data sent via Nightsocut shown on the watch, so GDH would be perfect. However, when she installed the WearOS version on the watch, there was no way to log in to her server (or enter LibreView data as well). Those options are only available in the phone version.

When you deal with all current issues you want to implement, can you, please, think about some way to allow logging into Nightscout or Libre Link Follower on the WearOS verision only?

**Comment by pachi81** [comment]
> It's me again :) Today I recommended GDH to somebody with iOS on her phone and a watch with WearOS. She wanted to get gluco data sent via Nightsocut shown on the watch, so GDH would be perfect. However, when she installed the WearOS version on the watch, there was no way to log in to her server (or enter LibreView data as well). Those options are only available in the phone version.
> 
> When you deal with all current issues you want to implement, can you, please, think about some way to allow logging into Nightscout or Libre Link Follower on the WearOS verision only?

Hi,

oh, I have never seen the wear app as standalone. But you are right, connected to an iPhone, you do not have any option to change the settings. You are right, I have to add the settings also to watch... 
The problem is to sync with phone version for android users... 

Another thing, can you update the polish strings:
https://github.com/pachi81/GlucoDataHandler/pull/117/files#diff-0908d478f1e1608a4d8bf0d6e84f3c23dd963a61f2ff17a7984af7e3e9f938d1

**Comment by froster82** [comment]
I translated the Polish parts.
Thanks for considering the above issue. I am no programmer, so I cannot help with practical solution of the syncing problem. The only idea I have is to intorduce som condition - wear os asks if there is a phone version, if yes, login options are inactive, if no - login options on wearOS become available. Could anything like that work?

**Comment by pachi81** [comment]
> I translated the Polish parts. 

Thank you very much for the quick translation!

>  The only idea I have is to intorduce some condition - wear os asks if there is a phone version, if yes, login options are inactive, if no - login options on wearOS become available. Could anything like that work?

This was also my first intention, but then I get a problem every time the phone is disconnect (ok, I can remember that there was a phone connected..., but as long I´m thinking about, I don´t like). 
Maybe syncing is not the biggest problem... To create input view for the settings I think is more complicated, as I do not have a lot of experience and on the tiny watch, every input is not so easy. 

But I will check, after I have created the alarm settings ;-)

**Pull request merged**
