### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by pachi81**

### CODE REVIEW

**Comment by pachi81** [comment]
@froster82 @dinizmauricio 
I uploaded the next test version for the next release. It includes the alarms. You can test it and translate the string, if you have some time. Don´t hurry, it is still in testing and we have time. I am "out of office" for the next 4 days... ;-)
So, just play around with the alarms.

**Comment by froster82** [comment]
@pachi81, I installed the newest version and will try to test it. I will also try to dig into the strings,also the English ones :)
Anyway, great work so far! Thanks!

**Comment by pachi81** [comment]
> @pachi81, I translated Polish parts, and I only have some small comments on alarms.
> 
> 1. When I press test it in Very low section, the alarm goes off on the phone and on the watch. When I press the pop up notification on the phone, the alarm on the phone is disabled, but it keeps going on the watch. It can only be stopped by pressing alarms icon in the GDH app on the phone. Pressing notification on the watch doesnot work
> 2. My watch is always in vibration only mode. Howeve, when I press Test it, the sound is played anyway on the watch. I suspect that you will get to this part in time, but just wanted to letyou know.

@froster82 I don't really understand what exact you have tried. Normally, if you dismiss notification on phone or watch, it should also disappear on the other device.
Can you please explain, what you have done on which device and please also send me the logs from both devices, after your test, so I can check it.

**Comment by pachi81** [comment]
@froster82 @dinizmauricio 
Hi, I think, I'm finishing the string values.
But no hurry, I have still some optimization and Bug fixes todo. 
So have a nice weekend! 😉

**Comment by froster82** [comment]
Hi! I will try to do my best as soon as possible :)

**Comment by froster82** [comment]
@pachi81, I updated the Polish strings and introduced some small corrections to some older ones.

**Comment by pachi81** [comment]
@froster82 @dinizmauricio 
Thank you both for such a fast translation!!!
Just one remark, is there a shorter one for
wear_complication_tap_action
as this is a button on wear?
I also have problems for german... 😕

**Comment by dinizmauricio** [comment]
> @froster82 @dinizmauricio Thank you both for such a fast translation!!! Just one remark, is there a shorter one for wear_complication_tap_action as this is a button on wear? I also have problems for german... 😕

@froster82, I also had doubts about this item, it's good you mentioned it! I tried to locate the screen, but was unsuccessful. Know where is?

**Comment by pachi81** [comment]
> > @froster82 @dinizmauricio Thank you both for such a fast translation!!! Just one remark, is there a shorter one for wear_complication_tap_action as this is a button on wear? I also have problems for german... 😕
> 
> @froster82, I also had doubts about this item, it's good you mentioned it! I tried to locate the screen, but was unsuccessful. Know where is?

Not yet present. In the next version it will be present.

**Comment by froster82** [comment]
@pachi81 now it might be a bit short, but with proper explanation in the next line everything should be ok.
Polish text translates literally to "after tap" - what happens after you tap.
Maybe German can also be something like that? Nach Tappen or something...

**Comment by pachi81** [comment]
> @pachi81 now it might be a bit short, but with proper explanation in the next line everything should be ok. Polish text translates literally to "after tap" - what happens after you tap. Maybe German can also be something like that? Nach Tappen or something...

It is the tap action, if you press on the complication. I thought about a sub menu for complications, but only have a switch and this button...
I will create a version tomorrow, so you can check it out.

**Comment by pachi81** [comment]
@froster82 @dinizmauricio 
New version is available, now. 😃

**Comment by froster82** [comment]
> It is the tap action, if you press on the complication.

Yes, I know. I only gave you the literal Polish version. Now it is "Działanie po naciśnięciu komplikacji" which on the watch screen does not look so bad after all. I would leave it as is. The only change for the final version needed is my slip with Alarms :D

**Comment by froster82** [comment]
@pachi81, one more thing I forgot to ask in terms of graphics. Do you need a double interline above the "Details" and "Connections" headers? This looks a bit off to me. Grey background is enough to make it visible, but the space - especially on the watch - takes a bit too much screen.

**Review by froster82 — APPROVED** [review]

**Comment by pachi81** [comment]
> @pachi81, one more thing I forgot to ask in terms of graphics. Do you need a double interline above the "Details" and "Connections" headers? This looks a bit off to me. Grey background is enough to make it visible, but the space - especially on the watch - takes a bit too much screen.

@froster82 I think it looks better, then without the space... And I want to have the same look on every device. I will check without the space, but I don´t think, that I will change it...

**Comment by froster82** [comment]
@pachi81 , behold my editing skills in Paint ;)
We can see how it looks like on a short notice.
ImportedPhoto_1714993774023
ImportedPhoto_1714993774023 — kopia

**Comment by pachi81** [comment]
Thank you and yes, I do not like the shorter one as there is no free space, to much text after text after text, ...
I think some space looks much better to me. But this is only my opinion...

**Comment by froster82** [comment]
For me space before the header looks a bit off, but this is just my opinion and you have the final say after all :)

**Comment by pachi81** [comment]
> For me space before the header looks a bit off, but this is just my opinion and you have the final say after all :)

@froster82 at the end, you are right ;-) New version is only...

**Comment by froster82** [comment]
> @froster82 at the end, you are right ;-) New version is only...

:D 
You know, Brian May supposedly used to complain and add his comments to Freddy Mercury and that way Queen always got a better song ;) 
Aaand today it is the 6th of May, Revenge of the 6th, so the dark side was with me.

**Comment by froster82** [comment]
@pachi81, Tap action button on the watch has the first version of my translation (Dzialanie po naciśnięciu komplikacji), but on the phone version there is the new shorter version (po naciśnięciu). 
Are there 2 strings for those buttons? Maybe I changed only one and forgot to change the other?

**Comment by pachi81** [comment]
> @pachi81, Tap action button on the watch has the first version of my translation (Dzialanie po naciśnięciu komplikacji), but on the phone version there is the new shorter version (po naciśnięciu). Are there 2 strings for those buttons? Maybe I changed only one and forgot to change the other?

Yes, there are 2 version. On phone there is a common one, which is clear, because of the content.
On watch, there is only a common menu, so there should be some more text.
But no problem it is not the final version...

**Comment by froster82** [comment]
Ok, I found the strings and made the wear shorter and the phone a bit longer.

**Comment by froster82** [comment]
@pachi81, I changed one last string. This will look better in practice.

**Comment by pachi81** [comment]
@froster82 @dinizmauricio One more string (last line). As I used an already existing one for icon, I only replaced the icon with trend-arrow. Please check, if it fits. Thank you!

**Comment by froster82** [comment]
@pachi81, Polish part fits perfect.

**Comment by pachi81** [comment]
@froster82 @dinizmauricio 
As I have forgot todo the WatchDrip+ part for alarms, I have to do another change.
Therefor I want to add an extra setting entry, where I put the settings for the color scheme and the setting for the big trend-arrow in. So I need 2 more translations:

- title: "**User interface**"
- description: "**General settings for the user interface of this application.**"

Thank you!

**Comment by froster82** [comment]
@pachi81, no problem
I think it will be faster if I can write them here:

title: Interfejs użytkownika
description: Ogólne ustawienia dotyczące interfejsu użytkownika tej aplikacji.

Cheers!

**Pull request merged**
