### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by pachi81**
Changes for PlayStore

### CODE REVIEW

**Comment by pachi81** [comment]
@froster82 Hi, for Google Playstore I have to remove the Android Auto part :-( 
So I put it in an extra app, which will receives the data from GlucoDataHandler and is only available in GitHub. 
Therefor I need to add some special settings (and a docu later).
Can you please translate the new settings: https://github.com/pachi81/GlucoDataHandler/pull/110/files#diff-0908d478f1e1608a4d8bf0d6e84f3c23dd963a61f2ff17a7984af7e3e9f938d1

If you are ready and I have test it, I will create a next try for PlayStore...

**Review by froster82 — APPROVED** [review]
Polish part done.

**Comment by pachi81** [comment]
> Polish part done.

@froster82 great, that was fast ;-)
Yeah, I´m also not happy, I also thought about to let it as it is, but a lot of people have problems with adb and wear installation.
And I also like to have it in playstore :-)
If I had known before, that it is so much effort, maybe I haven´t tried...

After everything is finished, there will be an additional change for the documentation here in github, to explain the people why I had to do this and how they can install the Android Auto part.

**Comment by froster82** [comment]
No problem. When you finish the English version, I will deal with the Polish one.
If GDH is in Play Store I think it will be used by a lot more people. Especially that now it would be the easiest way to follow kid's glucose levels with a widget - LibrelinkUp as a source and your app on parent's phone as a widget. I will make sure to write a tutorial for Polish users ;)
And one more thing - maybe for future development - is there any way for you to display glucose graph? Not just the values, but also a graph. This is just an idea I came up with, and not a necessary thing, but maybe this could be useful for somebody. That way xDrip would become really not necessary for day to day simple following.

**Comment by pachi81** [comment]
> No problem. When you finish the English version, I will deal with the Polish one. If GDH is in Play Store I think it will be used by a lot more people. Especially that now it would be the easiest way to follow kid's glucose levels with a widget - LibrelinkUp as a source and your app on parent's phone as a widget. I will make sure to write a tutorial for Polish users ;) And one more thing - maybe for future development - is there any way for you to display glucose graph? Not just the values, but also a graph. This is just an idea I came up with, and not a necessary thing, but maybe this could be useful for somebody. That way xDrip would become really not necessary for day to day simple following.

@froster82 Some people already asked for it, but such things are not so easy (I think). And the biggest problem is, that I not really use the graph, so I´m not so interested in :-)
At the moment, if people really need it, they can use the one from Juggluco, xDrip+ or LibreLinkUP...

**Comment by froster82** [comment]
Hehe, I understand completely :) That was just some food for thought ;)

**Comment by froster82** [comment]
@pachi81 I have one question. Would it be possible for you to implement alarms in GDH? It would ba a good feature for parents following the values of their kids. The kid sends their values to LibrelinkUp, the parent receives the values in GDH from LibrelinkUp. And the alarms would be activated by GDH not Librelinkup on the parent's phone. Would it be possible. Somebody on the Polish forum asked about such possibility, and I was sure it is possible. But I cannot fing the alarms feature.

**Comment by pachi81** [comment]
> @pachi81 I have one question. Would it be possible for you to implement alarms in GDH? It would ba a good feature for parents following the values of their kids. The kid sends their values to LibrelinkUp, the parent receives the values in GDH from LibrelinkUp. And the alarms would be activated by GDH not Librelinkup on the parent's phone. Would it be possible? Somebody on the Polish forum asked about such possibility, and I was sure it is possible. But I cannot find the alarms feature.

@froster82 Yes, it is possible and already on the roadmap for the next version.
Unfortunately I have some problems with the playstore policies and have todo some extra rounds, but as soon, this solved, I can continue with new features, like alarms...
But I think, not this year... ;-)

**Comment by froster82** [comment]
Maybe I have seen the entries about alarms in the strings, that is why I was sure it is already available :) Well, I know about bureaucracy quite a lot, because the Polish one is crazy as... well you know ;) We just have to wait and keep fingers crossed.

**Comment by pachi81** [comment]
> Maybe I have seen the entries about alarms in the strings, that is why I was sure it is already available :) Well, I know about bureaucracy quite a lot, because the Polish one is crazy as... well you know ;) We just have to wait and keep fingers crossed.

@froster82 Yes, the code for alarms is already present, but only used for vibration on wear and notification on Android Auto.
So I only need some configuration and some notification and sounds for phone...
As soon as my app is in the playstore, I will continue with this stuff.

**Comment by pachi81** [comment]
@froster82 Can you please change this file to fit polish: https://github.com/pachi81/GlucoDataHandler/blob/develop/GlucoDataAuto_PL.md

And hey, my app is now available in playstore: https://play.google.com/store/apps/details?id=de.michelinside.glucodatahandler

**Comment by froster82** [comment]
@pachi81, Polish version ready.
Congratulations on dealing with Google red tape :) I already updated my phone and watch via Play Store and it works.

**Comment by pachi81** [comment]
@froster82 Thank you! Also for having a look to the english version! My english is far away from perfect :-)
One more thing, can you have a look at line 29 in the polish version.

**Pull request merged**
