### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by pachi81**

### CODE REVIEW

**Comment by pachi81** [comment]
@froster82 New strings to translate. 
I also changed the existing string for the target range to very high and low to match the alarm strings:
https://github.com/pachi81/GlucoDataHandler/pull/156/commits/f54d45ffc2ab4e697113f9cf0cf0957913a51585#diff-0908d478f1e1608a4d8bf0d6e84f3c23dd963a61f2ff17a7984af7e3e9f938d1

Thank you very much!!!!

**Comment by pachi81** [comment]
@froster82 also the new ones at the end ;-)

**Comment by froster82** [comment]
Sorry about that. I did not scroll down to the end to check :)

**Comment by pachi81** [comment]
> Sorry about that. I did not scroll down to the end to check :)

@froster82 no problem ;-) 
I uploaded the new version to playstore for testing.

**Comment by pachi81** [comment]
@froster82 still one missing, I changed this morning. Sorry, I forgot to mention this change:
https://github.com/pachi81/GlucoDataHandler/blob/c8f7db199c87d6feced190318dce85fbbc62b43d/common/src/main/res/values-pl/strings.xml#L401

**Comment by froster82** [comment]
I will deal with it at home, because I am having trouble with editing the file on a mobile network.

**Comment by pachi81** [comment]
> I will deal with it at home, because I am having trouble with editing the file on a mobile network.

No problem, it is not urgent!

**Comment by froster82** [comment]
OK, done. I hope I have not missed anything else. This time I did not see all the changes in colour. Only some. And Github app is not as helpful as I thought :)

**Comment by pachi81** [comment]
@froster82 Thank you very much! I created a new version in Playstore, so you can check it.

**Pull request merged**
